project_id: 'arun-genai-bb'
credentials_json: './credentials/key.json'
site_search_datastore_id: 'moodys-search_1697576889487'
doc_search_datastore_id: 'hsbc-doc-search_1697815031642'
doc_search_bucket: 'financial-pdf-documents'
user_pseudo_id: '12345'